/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;

/**
 *
 * @author wellington
 */
public class TelaGenio extends javax.swing.JFrame {

	/**
	 * Creates new form TelaGenio
	 */
	public TelaGenio() {
		initComponents();
		jLabelFrase.setText("<html>Vou pensar em um valor entre <strong>1</strong> e <strong>5</strong>. Tene adivinhar</html>");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFrase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerValor = new javax.swing.JSpinner();
        jButtonPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFrase.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFrase.setText("Frase");
        jLabelFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 160, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/conversation.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wizard.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jSpinnerValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(jSpinnerValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jButtonPalpite.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButtonPalpite.setText("Palpite");
        jButtonPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPalpiteActionPerformed
        // TODO add your handling code here:
		double numero = 1 + Math.random() * (6 - 1);
		int valor = (int) numero;
		
		int numeroUsuario = Integer.parseInt(jSpinnerValor.getValue().toString());
		
		String f1 = "<html>ACERTOU!</html>";
		String f2 = "<html>ERROU! Eu pensei no valor " + valor + "</html>";
		
		String res = valor == numeroUsuario ? f1 : f2;
		
		jLabelFrase.setFont(new Font("Arial Black", Font.PLAIN, 16));
		
		jLabelFrase.setText(res);
    }//GEN-LAST:event_jButtonPalpiteActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaGenio().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPalpite;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFrase;
    private javax.swing.JSpinner jSpinnerValor;
    // End of variables declaration//GEN-END:variables
}
