/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author wellington
 */
public class TelaCalculadora extends javax.swing.JFrame {

	/**
	 * Creates new form TelaCalculadora
	 */
	public TelaCalculadora() {
		initComponents();
		jPanelCalcular.setVisible(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerValor = new javax.swing.JSpinner();
        jButtonCalcular = new javax.swing.JButton();
        jPanelCalcular = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelCubica = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelAbsoluto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDivisao = new javax.swing.JLabel();
        jLabelCubo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelQuadrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Super Calculadora");

        jLabel2.setText("Informe um valor: ");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabel8.setText("Raiz Quadrada");

        jLabel9.setText("Raiz Cúbica");

        jLabelCubica.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelCubica.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCubica.setText("0");

        jLabel11.setText("Valor Absoluto");

        jLabelAbsoluto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelAbsoluto.setForeground(new java.awt.Color(51, 51, 51));
        jLabelAbsoluto.setText("0");

        jLabel3.setText("Resto da Divisão por 2");

        jLabelDivisao.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelDivisao.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDivisao.setText("0");

        jLabelCubo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelCubo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCubo.setText("0");

        jLabel6.setText("Elevado ao Cubo");

        jLabelQuadrada.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelQuadrada.setForeground(new java.awt.Color(51, 51, 51));
        jLabelQuadrada.setText("0");

        javax.swing.GroupLayout jPanelCalcularLayout = new javax.swing.GroupLayout(jPanelCalcular);
        jPanelCalcular.setLayout(jPanelCalcularLayout);
        jPanelCalcularLayout.setHorizontalGroup(
            jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcularLayout.createSequentialGroup()
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAbsoluto)
                    .addComponent(jLabelCubica)
                    .addComponent(jLabelQuadrada)
                    .addComponent(jLabelDivisao)
                    .addComponent(jLabelCubo))
                .addGap(0, 182, Short.MAX_VALUE))
        );
        jPanelCalcularLayout.setVerticalGroup(
            jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcularLayout.createSequentialGroup()
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelCubo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelQuadrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelCubica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelAbsoluto))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCalcular))
                            .addComponent(jPanelCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
		//Fica visivel
		jPanelCalcular.setVisible(true);
		
		//pegar valor do spinner
		int valor = (int) jSpinnerValor.getValue();
		
		//resto da divisao
		int resto = valor % 2;
		jLabelDivisao.setText(Integer.toString(resto));
		
		//elevado ao cubo
		float cubo = (float) Math.pow(valor, 3);
		jLabelCubo.setText(String.format("%.2f", cubo));
		
		//raiz quadrada
		float quadrada = (float) Math.sqrt(valor);
		jLabelQuadrada.setText(String.format("%.2f", quadrada));
		
		//raiz cubica
		float cubica = (float) Math.cbrt(valor);
		jLabelCubica.setText(String.format("%.2f", cubica));
		
		//numero absoluto
		int absoluto = Math.abs(valor);			
		jLabelAbsoluto.setText(Integer.toString(absoluto));
		
    }//GEN-LAST:event_jButtonCalcularActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaCalculadora().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAbsoluto;
    private javax.swing.JLabel jLabelCubica;
    private javax.swing.JLabel jLabelCubo;
    private javax.swing.JLabel jLabelDivisao;
    private javax.swing.JLabel jLabelQuadrada;
    private javax.swing.JPanel jPanelCalcular;
    private javax.swing.JSpinner jSpinnerValor;
    // End of variables declaration//GEN-END:variables
}
